---
# Source: app/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-db
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: app-db-sa@storied-reserve-473208-t1.iam.gserviceaccount.com
---
# Source: app/templates/migrations-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-app-migrations
data:
  001_create_users_table.sql: |
    -- 001_create_users_table.sql
  
    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        name TEXT NOT NULL,
        email TEXT NOT NULL UNIQUE
    );
  002_add_age_to_users.sql: |
    -- 002_add_age_to_users.sql
  
    -- age 컬럼이 없으면 추가
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = 'users'
              AND column_name = 'age'
        ) THEN
            ALTER TABLE users
            ADD COLUMN age INT;
        END IF;
    END $$;
  003_set_default_age.sql: |
    -- 003_set_default_age.sql
  
    -- age 가 NULL 인 유저들 기본값 세팅
    UPDATE users
    SET age = COALESCE(age, 20);
---
# Source: app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: app
    app.kubernetes.io/name: app
---
# Source: app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-app
  labels:
    helm.sh/chart: app-0.1.0
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: app
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
        app.kubernetes.io/instance: release-name
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: app
          image: "docker.io/comrry/devops:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: APP_PORT
              value: "8080"
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "app"
            - name: DB_NAME
              value: "appdb"
            - name: REDIS_ADDR
              value: "redis-master.default.svc.cluster.local:6379"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: app-db-secret
                  key: password
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 150m
              memory: 128Mi

        # ✅ Cloud SQL Proxy Sidecar (DB 접속 담당)
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.10.1
          args:
            - "--private-ip"
            - "--auto-iam-authn"
            - "--port=5432"
            - "storied-reserve-473208-t1:asia-northeast3:devops-postgres"
          securityContext:
            runAsNonRoot: true
---
# Source: app/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - yong-dev.win
      secretName: app-tls
  rules:
    - host: yong-dev.win
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 8080
---
# Source: app/templates/backendconfig.yaml
# apiVersion: cloud.google.com/v1
# kind: BackendConfig
# metadata:
#   name: app-backendconfig
# spec:
#   healthCheck:
#     checkIntervalSec: 5
#     timeoutSec: 5
#     healthyThreshold: 2
#     unhealthyThreshold: 2
#     type: HTTP
#     requestPath: /healthz
#     port: 8080
---
# Source: app/templates/db-test.yaml
# # db-test.yaml
# apiVersion: v1
# kind: Pod
# metadata:
#   name: db-test
#   namespace: default
# spec:
#   serviceAccountName: app-db
#   restartPolicy: Never
#   containers:
#   - name: proxy
#     image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.10.1
#     args:
#       - "--instance=storied-reserve-473208-t1:asia-northeast3:devops-postgres"
#       - "--address=0.0.0.0"
#       - "--port=5432"
#     ports:
#       - containerPort: 5432
#   - name: psql
#     image: postgres:16
#     command: ["bash","-lc","sleep infinity"]
---
# Source: app/templates/loadgen-deploy.yaml
# # loadgen-deploy.yaml
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: load-generator
# spec:
#   replicas: 5   # 필요 시 10~20까지 올리기
#   selector:
#     matchLabels:
#       app: load-generator
#   template:
#     metadata:
#       labels:
#         app: load-generator
#     spec:
#       containers:
#         - name: loadgen
#           image: busybox:1.36
#           command: ["/bin/sh","-c"]
#           args:
#             - >
#               while true; do
#                 wget -q -O- http://app.default.svc.cluster.local:8080/ > /dev/null || true;
#               done
#           resources:
#             requests:
#               cpu: 20m
#               memory: 32Mi
#             limits:
#               cpu: 100m
#               memory: 64Mi
---
# Source: app/templates/certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-cert
  namespace: default
spec:
  secretName: app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - yong-dev.win
---
# Source: app/templates/clusterissuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: comrryy2@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
---
# Source: app/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-app-test-connection"
  labels:
    helm.sh/chart: app-0.1.0
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['release-name-app:8080']
  restartPolicy: Never
